dict: ['a', 'b', '>', '<', '!', '=', '1']
regular: !!str (a|b)*bb(>|<|>=|<=|!=|==)1
tranDicts:
 -
  a: 0
  b: 1
 -
  a: 0
  b: 2
 -
  a: 0
  b: 2
  '>': 3
  '<': 3
  '!': 4
  '=': 4
 -
  '=': 5
  '1': 6
 -
  '=': 5
 -
  '1': 6
 -

